package ar.edu.unlam.pb1;

public enum OPCION_DE_MENU {
AGREGAR_PROPIEDAD, MODIFICAR_PROPIEDAD, AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO, OBTENER_LISTADO_POR_UBICACION, BUSCAR_PROPIEDADES_POR_PRECIO, BUSCAR_PROPIEDADES_POR_UBICACION, REALIZAR_VENTA, REALIZAR_ALQUILER;
}

